name: nakama1
database:
  address:
    - "postgres:localdb@postgres:5432/nakama"

console:
  port: 7351
  username: admin@nakama.local
  password: password123

runtime:
  js_entrypoint: "build/index.js"

session:
  token_expiry_sec: 7200

socket:
  port: 7350
  response_headers:
    - "Access-Control-Allow-Origin=*"
    - "Access-Control-Allow-Headers=Authorization, Content-Type, User-Agent, X-Requested-With"
    - "Access-Control-Allow-Methods=GET, POST, PUT, PATCH, DELETE, OPTIONS"

match:
  input_queue_size: 128
